### ISSUE TITLE
Eliminar ficheros .db del repositorio

### ISSUE THREAD

**Issue by imartinezortiz** [jaimegonzalezfabregas/TFG-ASD-WebServer#1]
En general, los ficheros binarios no se deberían de meter en un repositorio de git, pero los ficheros .db de sqlite menos. Para tener gestionar la BD con sequelize es mejor utilizar [migrations y seeds de sequelize](https://sequelize.org/docs/v6/other-topics/migrations/).

**Comment by jgaldoo** [comment]
Ficheros eliminados, falta hacer migrations.
