### ISSUE TITLE
Mejoras en los pretotipos

### ISSUE THREAD

**Issue by imartinezortiz** [jaimegonzalezfabregas/TFG-ASD-WebServer#4]
En HTML5 tenemos una amplia gama de componentes <input> que hay que aprovechar, en particular para:
- [fechas](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)
- [horas](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time)
- [fecha-hora](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local)

Cuando el usuario sólo puede escoger de una selección específica de valores, utilizar mejor <select> y complementado con [select2](https://select2.org/)

**Comment by jgaldoo** [comment]
Ok, perfecto, gracias por la información.
Hemos empezado a aplicar las componentes de tiempo al tfg.
En principio, tenemos uno o dos sitios pensados en los que poder aplicar select2.
